POST  http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "testonildo@email.com",
    "name": "Testonildo",
    "password": "123789",
    "role": "admin"
}

###

POST http://localhost:3000/user/login 
Content-Type: application/json

{
    "email": "testonildo@email.com",
    "password":"123789"
}