POST http://localhost:3003/createUser
Content-Type: application/json

{
    "name": "testonildo",
    "email": "testo@gmail.com",
    "password": "111111"
}

###

GET http://localhost:3003/all
Content-Type: application/json

