GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE2MjM1M2JmLTk0ZmItNGI3YS1iYzM5LWQwYmE3MTljOGY1YyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MTMwMjcxNSwiZXhwIjoxNjYxMzAzMzE1fQ.K3nbXtMmN2boMNlGn7hkQihW-Y3V-8f6oNnknr5jwdc
Content-Type: application/json

###

POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "osbourne@oscorp.com" ,
   "password": "ihatepeter"
}

###

# @name signup

POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Alice",
	"email": "alice@lbn.com",
	"password": "123456"
}

###

@id = {{signup.response.body.newUser.id}}

PUT http://localhost:3003/user/edit/{{id}}
Content-Type: application/json

{
   "name": "Harry Osbourne" 
}