### GET PKM BY NAME

GET http://localhost:3306/pkm/data
Content-Type: application/json

{
    "name": "bu"
}

### GET PKM BY TYPE

GET http://localhost:3306/pkm/type
Content-Type: application/json

{
    "type": "fi"
}